### ISSUE TITLE
Building mex files for complete implementation

### ISSUE THREAD

**Issue by RegisStormayn** [Stage-VSS/matlab-lcr#4]
Hello, first of all thank you for providing this code. 
I am currently working on a project that requires me to control the DLP LightCrafter4500 with MATLAB, and considering the protocol of communication with the device that is used, I think that your approach is a really good one by directly using the source code of the GUI that is provided by TI. However I need a more extensive control of the DMD, so I would  like to continue the implementation of the functions in the source code (in dlpc350_api file). This what I have trouble with. I am working on Windows 10, MATLAB R2018b, with MinGW 6.3 installed and Microsoft Visual Studio 2022. I also have installed Microsoft Visual C++ 2010 and 2015. Your code is working perfectly fine, but I cannot find a way to create a mex file for even the simplest of the functions in the source code (fyi GetFirmwareVersion), even after a few hours spent on trying to understand mex and C++ compilation, since I didn't know any of it prior to this project. In the end after many attempts I got to this error which I am now stuck with for a while : "Path\lcrGetFirmwareVersion.obj:lcrGetFirmwareVersion.cpp:(.text+0x36):
undefined reference to `DLPC350_GetFirmwareVersion(unsigned int*)'
collect2.exe: error: ld returned 1 exit status"
The command I am typing is "mex lcrGetFirmwareVersion.cpp -ID:\PathToHeaders '-LD:\PathToLib' -llcr"
I am sorry to bother you with my request, but would you be so kind as to explain to me in a little more details the steps to create a mex file, in particular how to properly link libraries and how these libraries should have been compiled.
It seems pretty obvious that the problem lies in an incorrect import of the library in which the function should be defined, so should there be something like a "dlpc350_apiI.lib" file to include it ? I tried building one but it didn't work out, probably because of compilers incompatibility (got this warning when building the mex : "Warning: corrupt .drectve at end of def file", and then the function doesn't work when called).
I also tried rebuilding the lcr.dll library with "cl /Felcr /I hidapi-master/hidapi dlpc350_api.cpp dlpc350_usb.cpp hidapi-master/windows/hid.c SetupAPI.lib /LD", though mex command only accounts for .lib libraries as of my MATLAB version at least (I think this command builds the 2 at the same time).
Thank you in advance for your help and your time.
Respectfully 
R

**Comment by cafarm** [comment]
Hi R,

Have you tried calling the `make` function in the root of repository from MATLAB? It has been a while since I have tried to compile them but I was using that function to do it at the time. The lcr.dll and lcr.lib files are already included in the repo, so you shouldn't have to specify an external location. `make` will spit out the `mex` command it is attempting to use. You might just try deleting one of the existing mex binaries and calling `make` to see if you can get it to rebuild.

**Comment by RegisStormayn** [comment]
Hi, thank you very much for your response, I just tried removing the "lcrSetPowerMode.mexw64" from the repository and running the 

> make

 file, but I got the same type of error : 
"mex  -I"D:\DMDControl\matlab-lcr-master\api" -L"D:\DMDControl\matlab-lcr-master" -llcr lcrSetPowerMode.cpp
Building with 'MinGW64 Compiler (C++)'.
Error compiling 'lcrSetPowerMode.cpp'
C:\Users\LOCCO\AppData\Local\Temp\mex_117352718464707_21632\lcrSetPowerMode.obj:lcrSetPowerMode.cpp:(.text+0x52): undefined reference to `DLPC350_SetPowerMode(bool)'
collect2.exe: error: ld returned 1 exit status"

**Comment by RegisStormayn** [comment]
About the specification of the location you're right, since the "external" location specified was not external but simply that of the working directory, I just wrote it to be sure it was not an issue.

**Comment by cafarm** [comment]
Try using Visual Studio 2015 as your MEX compiler (should be able to change it with `mex -setup`). I vaguely remember having trouble linking against libraries when they were compiled with a different compiler. I believe this DLL was compiled with Visual Studio.

**Comment by RegisStormayn** [comment]
Thanks, indeed it worked to rebuild the file lcrSetPowerMode.mexw64, however when building my own, I now get this error : 
"Error using mex
lcrGetFirmwareVersion.cpp
D:\DMDControl\matlab-lcr-master\api\dlpc350_api.h(69): error C2065: 'HID_MESSAGE_MAX_SIZE'ÿ: undeclared identifier

**Comment by RegisStormayn** [comment]
Never mind that, there was a little error, now the mex file builds well (the function still doesn't work as planned but I'll look into it later). Again, thank you very much for your much appreciated help

**Comment by RegisStormayn** [comment]
Hello, to give you a little update, I have successfully built the mex files for the functions that I was interested in, 
and they **almost** all work, so now I have to do it in python as well, wish me luck
